### ISSUE TITLE
ARM64 container

### ISSUE THREAD

**Issue by isarrider** [tasmota/docker-tasmota#14]
Hi,

it would be awesome to add an ARM64 container to docker hub...
Is this possible?

BR,
Alex

**Comment by barbudor** [comment]
Why not just cloning the repo and building the image on your system?

**Comment by isarrider** [comment]
because so everybody can profit... ;)

**Comment by barbudor** [comment]
I believe you need an ARM64 platform to create the image
So blakadder doesn't have one or if github action doesn't provide such option, then it's may not be t be possible
I don't know if it is possible to cross build a docker image and I believe it's probably not possible because you need to run code such as 'apt install' in the target os

**Comment by isarrider** [comment]
it would be, e.g. with
`docker buildx build --platform linux/arm64,linux/arm/v7 -t docker-tasmota`
for arm64 and armv7 in the example above...
But I guess github actions build them anyway?

**Comment by blakadder** [comment]
i have no intention on adding it, container is build on my x86 machine and pushed to docker

**Comment by Jason2866** [comment]
added linux/arm64. There are no espressif toolchains available for arm/v7
